version: '2.31.0'
services:
  capstone_project:
<<<<<<< HEAD
    image: aravindmathes/dev:0.1
=======
    image: ${DOCKER_IMAGE}
>>>>>>> dev
    ports:
      - 8080:80
    volumes:
      - ./dependencies/nginx.conf:/etc/nginx/nginx.conf:ro

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    ports:
      - 9113:9113
    command:
      - -nginx.scrape-uri=http://localhost:80/stub_status
    depends_on:
      - capstone_project

<<<<<<< HEAD
=======
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    ports:
      - "8081:8081"
    command:
      - --port=8081
    volumes:
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /:/rootfs:ro

>>>>>>> dev
  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./dependencies/prometheus.yml:/etc/prometheus/prometheus.yml:ro
<<<<<<< HEAD
=======
      - ./dependencies/alert.rules.yml:/etc/prometheus/alert.rules.yml:ro
    depends_on:
      - alertmanager
      - cadvisor
>>>>>>> dev

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    depends_on:
<<<<<<< HEAD
      - prometheus
=======
      - prometheus
  
  alertmanager:
    image: prom/alertmanager:latest
    ports:
      - 9093:9093
    volumes:
      - ./dependencies/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    command:
      - --config.file=/etc/alertmanager/alertmanager.yml
>>>>>>> dev
